### ISSUE TITLE
Error creating view file

### ISSUE THREAD

**Issue by xstreamka** [insperedia/yiidea-support#1]
After clicking Create, a file is created in the wrong path, and the file itself is empty, without annotations.

![image](https://github.com/insperedia/yiidea-support/assets/73387820/86869e89-66c5-4710-bd8c-ffb789a4c845)

![image](https://github.com/insperedia/yiidea-support/assets/73387820/d799ab15-e992-4871-a4de-2cd3643ff197)

![image](https://github.com/insperedia/yiidea-support/assets/73387820/16803c56-ca61-4573-a82b-2af166c66961)

**Comment by insperedia** [comment]
Thank you for the issue. You did not specify the controller path but specified that the bug is the same as  #3 .  I will make a fix according to #3

**Comment by xstreamka** [comment]
> Thank you for the issue. You did not specify the controller path but specified that the bug is the same as #3 . I will make a fix according to #3

Standard path: /app/frontend/controllers/SiteController.php

**Comment by insperedia** [comment]
Fixed in 1.0.8
