### ISSUE TITLE
Rendering View File that is using Alias

### ISSUE THREAD

**Issue by nhatzbulawan** [insperedia/yiidea-support#10]
It seems like there is an issue when using the @app alias. It cannot find the file, even though it exists in the module directory. 

![image](https://github.com/insperedia/yiidea-support/assets/3007744/1bccaf30-7a0e-4a1c-bfb3-a9d834ac541b)

**Comment by insperedia** [comment]
Thank you for the issue, aliases currently not supported directly because actual paths could be different during runtime.
But this can be fixed in future versions.
Could you please provide full path from the root of the project of the view file presented on screenshot.

**Comment by nhatzbulawan** [comment]
Hi @insperedia ,

The one shown is the full path from the root project, where the @app Alias is.

It is $rootProject/modules/user/views/default/user_menu.php

**Comment by insperedia** [comment]
I mean file which references user_menu.php. I guess it is in standard location like @app/views/layouts/main.php or something similar.
Anyway, I checked your case, and see the problem. 
I will implement it in future versions.

**Comment by nhatzbulawan** [comment]
Hi @insperedia, 

I'm sorry for the misunderstanding. It is located in @app/modules/admin/default/views/main.php.

**Comment by insperedia** [comment]
The bug was fixed in version 1.0.11 which will be available shortly after JetBrains Marketplace approval.
