### ISSUE TITLE
"Missed View variable declarations" always show

### ISSUE THREAD

**Issue by mzdani** [insperedia/yiidea-support#16]
Hello, nice and thanks for the plugin :thumbsup:

Btw, when a view file doesn't have required variable, there is an error bar show up. And (sometimes) when I add missed variable on to the view doc block, warning about missed view variable still there.

![2024-06-24 09-49-35 GIT_Bootstrap_5 – _checkout php](https://github.com/insperedia/yiidea-support/assets/1886263/327cf71d-47e4-4a7a-b2e2-ba648fd3be90)

even when I try to click on `Add missed variable declarations`, it still there with duplication with existed one.

![2024-06-24 09-49-48 GIT_Bootstrap_5 – _checkout php(1)](https://github.com/insperedia/yiidea-support/assets/1886263/1f50f591-9595-437a-bad7-509eafad74c1)

I try to `Invalidate caches` and restart ide, but it still there. Like I said earlier, it's not always error like this. Even I don't know how to "always" create the problem. But it seems that plugin failed to detect already existed variable on view file. 

Is it a bug or maybe there is some setting that I don't know?

Thanks :grin:

**Comment by verifiera** [comment]
The plug-in uses PHPStorm's built-in PHP parser to check if a view has variables. It would be nice to provide more information.
The first thing you can do is to check the IDE "see" variable. You can try to see methods for $formModel by typing $formModel->, so you should see a dropdown for this object method.

**Comment by mzdani** [comment]
If I type `$formModel->` there is autocomplete for this variable. 

![Screenshot at Jun 24 19-31-44](https://github.com/insperedia/yiidea-support/assets/1886263/cbe19803-73c6-4329-9216-daafdd2bb4d7)

I try to disabled all external plugins and then re-enable it, restart IDE, and the warning bar is gone. I'm sorry sire as I can't provide more information about this for now.

Thank you for this awesome plugin 👍🏼 , I'll close this because lacking of information 😁
