### ISSUE TITLE
Migrations in Docker

### ISSUE THREAD

**Issue by xstreamka** [insperedia/yiidea-support#2]
In a project that uses Docker, migrations do not work, since the connection is made through an ENV file.
Is it possible to somehow make connections between migrations and ENV?

migrations tools:
![image](https://github.com/insperedia/yiidea-support/assets/73387820/64e0a871-a1c3-4397-be85-432624ef105d)

config file: app/common/config/main-local.php
![image](https://github.com/insperedia/yiidea-support/assets/73387820/4a4a6570-b22f-4940-9be4-b0c2cb56bfdc)

**Comment by insperedia** [comment]
Thank you for the issue. The plugin runs "php yii migrate" in the background, so there should not be a problem with .env.
Are you able to execute migrations by running "php yii migrate" on local machine? 
Or you execute the "yii migrate" command inside the container

**Comment by xstreamka** [comment]
> Or you execute the "yii migrate" command inside the container

That's right, I'm working with migrations inside a container.
Local php does not see ENV and also results in an error.

**Comment by xstreamka** [comment]
I figured it out, everything works, you just need to register the connection in a local file without variables.
