### ISSUE TITLE
View Path issue for modules

### ISSUE THREAD

**Issue by nhatzbulawan** [insperedia/yiidea-support#3]
![image](https://github.com/insperedia/yiidea-support/assets/3007744/d644c6dc-038e-4dcd-8dd1-6a033b513e03)

The controller is inside the module "member". This is the namespace of the controller app/modules/member/controllers.

The file exists in app/modules/member/views/metabolic-formulations/access.php

**Comment by xstreamka** [comment]
@nhatzbulawan the error is already [known](https://github.com/insperedia/yiidea-support/issues/1)

**Comment by verifiera** [comment]
Thank you for the issue. I will check the problem.

**Comment by insperedia** [comment]
Thank you for the issue. I will check the problem.

**Comment by insperedia** [comment]
Fix is in testing

**Comment by insperedia** [comment]
Fixed in 1.0.8
