### ISSUE TITLE
Problems with PhpStorm

### ISSUE THREAD

**Issue by xstreamka** [insperedia/yiidea-support#6]
Today I noticed that the IDE does not highlight the code, tooltips, method transitions, etc. do not work.
This happened when some plugin broke or overloaded the system.
When I disabled this plugin, everything worked immediately.
When I turned it back on, the problems started again immediately.

What information should I provide, maybe some logs?

PhpStorm 2023.3.3
Build #PS-233.14015.96, built on January 24, 2024
Runtime version: 17.0.9+7-b1087.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.0-27-amd64
GC: G1 Young Generation, G1 Old Generation
Memory: 12000M
Cores: 16
Registry:
  debugger.watches.in.variables=false
  run.processes.with.pty=TRUE
Non-Bundled Plugins:
  main.kotlin.com.jimschubert.intellij.swaggercodegen (4.3.1-p0)
  org.jetbrains.intellij.scripting-javascript (1.2)
  com.intellij.ideolog (222.3.1.0)
  dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
  pers.fw.doc_en (1.1)
  ru.adelf.idea.dotenv (2024.1)
  net.king2500.plugins.PhpAdvancedAutoComplete (1.1.0)
  de.espend.idea.php.annotation (9.4.0)
  com.insperedia.yiiFramework (1.0.5)
  cn.yiiguxing.plugin.translate (3.5.6)
  com.ppolivka.plugin.gitcleaner (1.1.4)
Current Desktop: GNOME

**Comment by insperedia** [comment]
Was it an Yii project?

**Comment by insperedia** [comment]
Can you also check if IDE consumes CPU more than usual? 

If you can, you can try to check if there is any conflict with another plugin by deactivation all plugins except Yii Support.

**Comment by xstreamka** [comment]
It seems to have been fixed by deleting the .idea folder
